@echo off
ECHO Building DuckTails...
pyinstaller --onefile --windowed --icon=.\dist\icon.ico DuckyTails.py
ECHO Building DuckyFlash...
pyinstaller --onefile --icon=.\icons\DuckyFlash.ico DuckyFlash.py
ECHO Building DuckyEncoder...
pyinstaller --onefile --icon=.\icons\DuckyEncoder.ico DuckyEncoder.py
ECHO Cleaning Files...
clean.bat
ECHO Quack Done! ;)