@echo off
ECHO Building DuckTails...
pyinstaller --onefile --windowed --icon=.\dist\icon.ico DuckyTails.py
ECHO Building DuckyFlash...
pyinstaller --onefile --icon=.\icons\DuckyFlash.ico --distpath .\Tools DuckyFlash.py
ECHO Building DuckyEncoder...
pyinstaller --onefile --icon=.\icons\DuckyEncoder.ico --distpath .\Tools DuckyEncoder.py
ECHO Cleaning Files...
clean.bat
ECHO Quack Done! ;)